### ISSUE TITLE
Error: Command failed (1) In addition: Warning message: GitHub repo contains submodules, may not function as expected! 

### ISSUE THREAD

**Issue by robertregalado** [wush978/Rcereal#11]
devtools::install_github('dmlc/xgboost', subdir = 'R-package')
Downloading GitHub repo dmlc/xgboost@master
from URL https://api.github.com/repos/dmlc/xgboost/zipball/master
WARNING: Rtools is required to build R packages, but no version of Rtools compatible with R 3.3.1 was found. Rtools 3.4 was previously installed in c:/Rtools but now that directory contains Rtools 3.3.

Please download and install Rtools 3.4 from http://cran.r-project.org/bin/windows/Rtools/.
Installing xgboost
"C:/PROGRA~1/R/R-33~1.1/bin/i386/R"  \
  --no-site-file --no-environ  \
  --no-save --no-restore --quiet  \
  CMD INSTALL  \
  "C:/Users/hp/AppData/Local/Temp/Rtmpcr4Ugo/devtools10b01a4949f9/dmlc-xgboost-80c8515/R-package"  \
  --library="C:/Users/hp/Documents/R/win-library/3.3"  \
  --install-tests 

* installing *source* package 'xgboost' ...
** libs
Warning: running command 'make -f "Makevars.win" -f "C:/PROGRA~1/R/R-33~1.1/etc/i386/Makeconf" -f "C:/PROGRA~1/R/R-33~1.1/share/make/winshlib.mk" CXX='$(CXX1X) $(CXX1XSTD)' CXXFLAGS='$(CXX1XFLAGS)' CXXPICFLAGS='$(CXX1XPICFLAGS)' SHLIB_LDFLAGS='$(SHLIB_CXX1XLDFLAGS)' SHLIB_LD='$(SHLIB_CXX1XLD)' SHLIB="xgboost.dll" ' had status 127
ERROR: compilation failed for package 'xgboost'
* removing 'C:/Users/hp/Documents/R/win-library/3.3/xgboost'
* restoring previous 'C:/Users/hp/Documents/R/win-library/3.3/xgboost'
Error: Command failed (1)
In addition: Warning message:
GitHub repo contains submodules, may not function as expected!

**Comment by robertregalado** [comment]
I'm installating devtools::install_github ('dmlc/xgboost', subdir = 'R-package') but  an error occur Error: Command failed (1)
In addition: Warning message:
GitHub repo contains submodules, may not function as expected!

Hope anyone can help?

**Comment by wush978** [comment]
This is not an issue of Rcereal.
